default: &default
  adapter: mysql2
  pool: 5
  timeout: 3000
  encoding: utf8
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>

development:
  <<: *default
  database: taptappun_development

test:
  <<: *default
  database: taptappun_test

production:
  <<: *default
  database: taptappun_production
